### ISSUE TITLE
Suggestion: mutable LookupMap

### ISSUE THREAD

**Issue by gmpassos** [agilord/lookup#1]
The package description states that it provides immutable data structures, which is a significant advantage.

This reminded me of an approach I used to create a highly efficient index for a private database. In this setup, the index was split into two parts: a sorted/clean part and an unsorted/dirty part. The index would only be rebuilt when the dirty part grew large enough (over 100 entries), at which point all entries were merged into the sorted/clean part. During lookups, the system would first search in the sorted/clean part, and, if not found, then check the dirty part.

This index was designed to be accessed directly on disk, with minimal memory usage, as only specific portions needed to be loaded when necessary. The result was an extremely fast indexing system.

It seems that with "immutable" structures, it may be possible to create indexes with similar behavior. Therefore, I suggest adding an immutable `LookupMap` and a mutable `LookupMap` to your package, following the simple approach described above.

**Comment by isoos** [comment]
I think the combined approach is still alive in many systems, and yes, we should have more diverse structures to support it, and I'm happy to take PRs that help these use cases.

However, in the few cases I have seen so far, the mutable parts were mostly the following: write-ahead logs + maybe a lightweight data structure on top of + on-demand calculation which may not have been that efficient compared to the immutable structure. I'm not entirely sure that the mutable versions should be 1:1 version of the immutable ones, they could be very simple, as the amount of data they need to handle should be limited and small.

While I think these are good to have features, I don't consider them as high priority right now, I'd rather focus on the planned features. I can be convinced otherwise, and I also take PRs that provide the mutable parts.

**Comment by gmpassos** [comment]
>  I'm not entirely sure that the mutable versions should be 1:1 version of the immutable ones, they could be very simple, as the amount of data they need to handle should be limited and small.
> 

Yes, the "unsorted/dirty" version should focus on fast insertion of new values.

I will send a PR with a simple implementation of a mutable version that uses "clean" and "dirty" parts internally. The clean part will use the `BPTreeV1` implementation, while the dirty part will be a simple sequence/list of entries using similar serialization.

**Comment by gmpassos** [comment]
I was looking into `BPTreeV1.build`, and with a small adjustment to the serialization order, it would be able to append an entry (`keepEntryOrder: false`). What do you think?

**Comment by gmpassos** [comment]
PR: https://github.com/agilord/lookup/pull/2 👀 @isoos

**Comment by isoos** [comment]
I'm not convinced that the mutable state handling should be tied to the B+tree implementation. I'd rather imagine the following:

We could have a `MutableLookupMap` as a single data structure for in-memory Dart objects, no pre-calculated binary lookup, optimized for simplicity when updating and also acceptable read speed. It could be just a simple list with linear lookup. It may get new values or updates on existing ones, and it should also keep track of the removed keys. The intent of this structure is to eventually get it merged with the previously built  index.

Operations to it are preceded to appending to a persistent write-ahead-log for durability, which is likely written in separate segment files as one segment gets frozen (scheduled for merging with the previous ones) and a new is opened. For a hybrid index, one will have pre-built index(es) + frozen WAL segments + the latest WAL segment with mutable in-memory state. Updates happen only on the latest WAL segment.

So this `ChainedLookupMap` may keep track of all of these states and indexes, handling the gets (chained through all of the operations) and update requests. We may also want to support conditional updates in one way or another.

To make it more customizable, it could have customizable indexing strategies (e.g. merge with the largest, or merge the smaller ones first), and it could also upgrade the indexes as they are updated (merged) to a different/newer version, depending on the application's needs.

As you can see, this is a much larger scope, but it is mostly separate from the tree index, rather a higher-level organization of it. I think it is worth to look into implementing this, but I would imagine that this will be not a single PR and would have lots of iterations and would require a lots of tests.

**Comment by gmpassos** [comment]
> I'm not convinced that the mutable state handling should be tied to the B+tree implementation. I'd rather imagine the following:
> 

I was thinking the same way, but considering the current state of B+tree serialization, it's very simple to support these new operations without needing to re-implement another collection.

**Comment by isoos** [comment]
> I was thinking the same way, but considering the current state of B+tree serialization, it's very simple to support these new operations without needing to re-implement another collection.

I think it looks simple, but it won't actually be with a full implementation, especially when you consider keeping track of the deleted keys. There are way too many failure cases already, having a simple implementation is much more preferable in the long term.

**Comment by gmpassos** [comment]
> ...especially when you consider keeping track of the deleted keys.

To me, a deleted key is simply an entry that remains, but with a value in its serialization indicating it's deleted, without needing to modify other regions. You could also rollback a key deletion changing one byte.

**Comment by isoos** [comment]
> To me, a deleted key is simply an entry that remains, but with a value in its serialization indicating it's deleted, without needing to modify other regions. You could also rollback a key deletion changing one byte.

How do you differentiate between a valid value of an empty byte array and a deleted key? They have different semantic meaning.

Also: I'm pretty sure that whatever may work in the case of the B+tree, it may not work that well for other planned structures. The main feature here is a 100% read-optimized and efficient data structure, and I don't see that happening with mixed goals.

**Comment by gmpassos** [comment]
About the deleted value, since you are using an unsigned int LEB28, you can save deleted as 0, empty list as 1, or a list length as (1 + length).

**Comment by isoos** [comment]
> About the deleted value, since you are using an unsigned int LEB28, you can save deleted as 0, empty list as 1, or a list length as (1 + length).

`varint` is used in many places, not entirely sure which list you are referring to. But it is suboptimal in every case:
- The implementation becomes a bit more complex: extra checks on each lookup.
- The storage becomes a bit less efficient as `varint` will use an extra byte in cases where it was just below the threshold (e.g. 127 vs 128).

I get it that it is not that much, and if I squint enough, I see where you want to head with this. But I want to optimize *only* for the lookup performance and efficiency, mutable state is an afterthought and I don't want to make *any* tradeoff for that. I am happily sharing these under a permissible license, you are free to take it and modify it to your liking.
